[hooks]
pre-commit = "cargo sync-readme && git add README.md"
pre-push = """\
    cargo fmt -- --check \
    && cargo test --all-features \
    && cargo test --examples \
    && cargo clippy -- -D warnings \
    && cargo clippy --examples -- -D warnings \
    && cargo sync-readme -c \
    """

[logging]
verbose = true
